### ISSUE TITLE
[1.15.2] Something in the interaction of Tetraits and other mods are breaking the stonecutter

### ISSUE THREAD

**Issue by jarquafelmu** [eutropius225/Tetraits#1]
With the tetraits the stonecutter loses it's recipes. without it then it has it's recipes

https://www.curseforge.com/minecraft/modpacks/the-briar-patch/files - Link to the modpack. Use version 1.0.15

**Comment by eutro** [comment]
Closing; supposedly this was not an issue with this mod in the first place.
